/**
 * Narrative draft generation (model-routed: narrative tier).
 *
 * Drafts the prose sections of a lender package from deal.json facts ONLY.
 * The model receives the extracted data and audit context, not the raw
 * documents, and is instructed to use nothing else. Output is a DRAFT the
 * human owns; the judgment calls (rating, recommendation) stay human.
 *
 * Voice: Mosaic rules. Plain factual statements. No em-dashes. No
 * exclamation points. No superlatives. M for thousands, MM for millions.
 */

import { Deal } from '../core/schemas';
import { callJson, LlmUsage } from '../llm/client';
import { describeBridgePricing } from '../core/market-config';

const SCHEMA = {
  type: 'object',
  additionalProperties: false,
  properties: {
    executiveSummary: { type: 'string' },
    propertyOverview: { type: 'string' },
    financialAnalysis: { type: 'string' },
    risksAndMitigants: { type: 'string' },
    dataGaps: { type: 'string', description: 'documents or fields still needed, as a bulleted list' },
  },
  required: ['executiveSummary', 'propertyOverview', 'financialAnalysis', 'risksAndMitigants', 'dataGaps'],
};

const SYSTEM = `You draft the prose sections of a commercial real estate lender package for Mosaic Capital Solutions.
Hard rules:
- Use ONLY the facts provided in the input JSON. If a fact is not provided, do not state it. List missing items in dataGaps instead.
- Financial notation: M for thousands, MM for millions (e.g. 18.4MM, 750M).
- Plain factual statements. No em-dashes. No exclamation points. No superlatives or hype language.
- Never state a risk rating or a credit recommendation. That is the human's call.
- Where a number is a proxy or low confidence, say so plainly.
- Each section 80-200 words. dataGaps is a markdown bulleted list.`;

export interface NarrativeResult {
  markdown: string;
  html: string;
  usage: LlmUsage;
}

/** Styled HTML rendering: boxed sections, DRAFT ribbon, data-gaps callout. */
function renderHtml(dealName: string, model: string, sections: Record<string, string>): string {
  const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;');
  const para = (s: string) => esc(s).split(/\n{2,}/).map(p => `<p>${p.replace(/\n/g, '<br>')}</p>`).join('');
  const gapsList = esc(sections.dataGaps)
    .split('\n').map(l => l.replace(/^\s*[-*]\s*/, '').trim()).filter(Boolean)
    .map(l => `<li>${l}</li>`).join('');
  const box = (title: string, body: string) =>
    `<section><h2>${title}</h2>${body}</section>`;
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(dealName)} - Package Narrative (DRAFT)</title>
<style>
  :root { --navy:#1a5c9e; --navy-dark:#123f6d; --ink:#1c2733; --mid:#5b6b7c; --line:#d7dee6; --warn-bg:#fff7e0; --warn-line:#e0b64a; }
  body { font-family: Georgia, 'Times New Roman', serif; color: var(--ink); max-width: 820px; margin: 2rem auto 5rem; padding: 0 1.4rem; line-height: 1.65; background:#fbfcfd; }
  header { border-bottom: 3px solid var(--navy); padding-bottom: 1rem; margin-bottom: 1.6rem; }
  h1 { font-size: 1.65rem; color: var(--navy-dark); margin: 0 0 .3rem; }
  .meta { font-family: system-ui, sans-serif; font-size: .8rem; color: var(--mid); }
  .ribbon { display:inline-block; font-family: system-ui, sans-serif; font-weight:700; font-size:.75rem; letter-spacing:.12em; color:#fff; background: var(--warn-line); padding:.25rem .9rem; border-radius:3px; margin-bottom:.6rem; }
  section { background:#fff; border:1px solid var(--line); border-left:4px solid var(--navy); border-radius:6px; padding:1.1rem 1.4rem; margin-bottom:1.1rem; box-shadow:0 1px 3px rgba(20,40,70,.06); }
  h2 { font-family: system-ui, sans-serif; font-size:.85rem; letter-spacing:.1em; text-transform:uppercase; color:var(--navy); margin:0 0 .6rem; }
  p { margin:.5rem 0; }
  .gaps { border-left-color: var(--warn-line); background: var(--warn-bg); }
  .gaps ul { margin:.4rem 0 .2rem 1.2rem; padding:0; }
  .gaps li { margin:.25rem 0; }
  footer { font-family: system-ui, sans-serif; font-size:.75rem; color:var(--mid); border-top:1px solid var(--line); padding-top:.8rem; margin-top:2rem; }
</style></head><body>
<header>
  <div class="ribbon">DRAFT - ANALYST REVIEW REQUIRED</div>
  <h1>${esc(dealName)}</h1>
  <div class="meta">Lender package narrative. Facts sourced from deal.json only. Generated by ${esc(model)}.
  Risk rating and recommendation intentionally absent: the credit call stays with the analyst.</div>
</header>
${box('Executive Summary', para(sections.executiveSummary))}
${box('Property Overview', para(sections.propertyOverview))}
${box('Financial Analysis', para(sections.financialAnalysis))}
${box('Risks and Mitigants', para(sections.risksAndMitigants))}
<section class="gaps"><h2>Data Gaps - Request Before Routing</h2><ul>${gapsList}</ul></section>
<footer>Mosaic Capital Solutions. Every number traces to a source document with confidence recorded in the workbook Audit sheet.</footer>
</body></html>`;
}

export async function generateNarrative(deal: Deal): Promise<NarrativeResult> {
  const facts = {
    name: deal.name,
    assetType: deal.assetType,
    location: deal.location,
    askingPrice: deal.askingPrice,
    hotel: deal.extracted.hotel,
    noi: deal.extracted.t12?.noi,
    rentRollSummary: deal.extracted.rentRoll
      ? {
          units: deal.extracted.rentRoll.tenants?.length,
          occupancyRate: deal.extracted.rentRoll.occupancyRate,
          effectiveGrossRent: deal.extracted.rentRoll.effectiveGrossRent,
        }
      : undefined,
    screen: deal.underwriting.screen
      ? {
          keyMetrics: deal.underwriting.screen.verdict ? deal.underwriting.screen.keyMetrics : undefined,
          killFlags: deal.underwriting.screen.killFlags?.filter(f => f.triggered),
          confidence: deal.underwriting.screen.confidenceSummary,
        }
      : undefined,
    marketPricing: describeBridgePricing(),
    extractedNotes: (deal.extracted.notes ?? []).map(n => ({ field: n.field, value: n.extractedValue, confidence: n.confidence })),
  };

  const { data, usage } = await callJson<{
    executiveSummary: string;
    propertyOverview: string;
    financialAnalysis: string;
    risksAndMitigants: string;
    dataGaps: string;
  }>(
    'narrative',
    SYSTEM,
    `Draft the package sections for this deal:\n${JSON.stringify(facts, null, 1)}`,
    'package_narrative',
    SCHEMA,
    2500
  );

  const markdown = [
    `# ${deal.name} - Lender Package Narrative`,
    '',
    `> DRAFT generated ${new Date().toISOString().substring(0, 10)} by ${usage.model}. Facts sourced from deal.json only.`,
    `> Judgment sections (risk rating, recommendation) are intentionally absent: human owns them.`,
    '',
    '## Executive Summary', '', data.executiveSummary, '',
    '## Property Overview', '', data.propertyOverview, '',
    '## Financial Analysis', '', data.financialAnalysis, '',
    '## Risks and Mitigants', '', data.risksAndMitigants, '',
    '## Data Gaps', '', data.dataGaps, '',
  ].join('\n');

  const html = renderHtml(deal.name, usage.model, data);

  return { markdown, html, usage };
}
