/**
 * Screen Report Generator
 * Produces screen.md output
 */

import { Deal, ScreenOutput, KeyMetric, KillFlag } from '../core/schemas';
import { RISK_SCORE_DESCRIPTIONS } from '../core/doctrine';
import { formatConfidence } from '../core/confidence';

// ============================================================================
// Generate screen report
// ============================================================================

export function generateScreenReport(deal: Deal, screen: ScreenOutput): string {
  const lines: string[] = [];
  
  // Header
  lines.push(`# Deal Screening Report: ${deal.name}`);
  lines.push('');
  lines.push(`**Asset Type:** ${deal.assetType}`);
  lines.push(`**Screened:** ${new Date(screen.executedAt).toLocaleString()}`);
  lines.push('');
  
  // Verdict Section
  lines.push('---');
  lines.push('');
  lines.push('## Verdict');
  lines.push('');
  lines.push(`### ${screen.verdict}`);
  lines.push('');
  
  const riskDesc = RISK_SCORE_DESCRIPTIONS[screen.riskScore];
  lines.push(`**Risk Score:** ${screen.riskScore}/5 — ${riskDesc?.label || 'Unknown'}`);
  lines.push('');
  lines.push(`> ${riskDesc?.description || ''}`);
  lines.push('');
  lines.push(`**Rationale:** ${screen.riskScoreRationale}`);
  lines.push('');
  
  // Adaptive adjustments if any
  if (screen.adaptiveAdjustments && screen.adaptiveAdjustments.length > 0) {
    lines.push('**⚠️ Adaptive Stress Applied:**');
    for (const adj of screen.adaptiveAdjustments) {
      lines.push(`- ${adj}`);
    }
    lines.push('');
  }
  
  // Kill Criteria Section
  lines.push('---');
  lines.push('');
  lines.push('## Kill Criteria Analysis');
  lines.push('');
  
  const triggeredKills = screen.killFlags.filter(k => k.triggered);
  const passedKills = screen.killFlags.filter(k => !k.triggered);
  
  if (triggeredKills.length > 0) {
    lines.push('### ⛔ Triggered Flags');
    lines.push('');
    for (const kill of triggeredKills) {
      const severity = kill.severity === 'hard' ? '🔴 HARD KILL' : '🟠 SOFT KILL';
      lines.push(`#### ${severity}: ${kill.criterion}`);
      lines.push('');
      lines.push(`**Reason:** ${kill.reason}`);
      lines.push('');
      if (kill.dataNeededToOverturn) {
        lines.push(`**To Overturn:** ${kill.dataNeededToOverturn}`);
        lines.push('');
      }
    }
  } else {
    lines.push('✅ No kill criteria triggered.');
    lines.push('');
  }
  
  if (passedKills.length > 0) {
    lines.push('### ✅ Passed Criteria');
    lines.push('');
    for (const kill of passedKills) {
      lines.push(`- **${kill.criterion}:** ${kill.reason}`);
    }
    lines.push('');
  }
  
  // Key Metrics Section
  lines.push('---');
  lines.push('');
  lines.push('## Key Metrics');
  lines.push('');
  lines.push('| Metric | Value | Confidence | Assessment | Notes |');
  lines.push('|--------|-------|------------|------------|-------|');
  
  for (const [key, metric] of Object.entries(screen.keyMetrics)) {
    const value = formatMetricValue(metric);
    const conf = formatConfidence(metric.value.confidence);
    const assessment = formatAssessment(metric.assessment);
    const notes = metric.benchmark || (metric.value.isProxy ? '⚠️ Proxy value' : '');
    lines.push(`| ${metric.name} | ${value} | ${conf} | ${assessment} | ${notes} |`);
  }
  lines.push('');
  
  // Proxy values note
  const hasProxies = Object.values(screen.keyMetrics).some(m => m.value.isProxy);
  if (hasProxies) {
    lines.push('*⚠️ Some values are proxies due to missing data. See audit log for methodology.*');
    lines.push('');
  }
  
  // Data Quality Section
  lines.push('---');
  lines.push('');
  lines.push('## Data Quality Assessment');
  lines.push('');
  lines.push(`**Overall Confidence:** ${formatConfidence(screen.confidenceSummary.overall)}`);
  lines.push('');
  
  lines.push('### Confidence by Category');
  lines.push('');
  for (const [category, conf] of Object.entries(screen.confidenceSummary.byCategory)) {
    const bar = generateConfidenceBar(conf);
    lines.push(`- **${capitalize(category)}:** ${bar} ${formatConfidence(conf)}`);
  }
  lines.push('');
  
  if (screen.confidenceSummary.criticalGaps.length > 0) {
    lines.push('### 🚨 Critical Data Gaps');
    lines.push('');
    for (const gap of screen.confidenceSummary.criticalGaps) {
      lines.push(`- ${gap}`);
    }
    lines.push('');
  }
  
  if (screen.confidenceSummary.dataRequests.length > 0) {
    lines.push('### 📋 Recommended Data Requests');
    lines.push('');
    for (const request of screen.confidenceSummary.dataRequests) {
      lines.push(`- [ ] ${request}`);
    }
    lines.push('');
  }
  
  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*Generated by Mosaic Underwriting System*');
  lines.push('');
  lines.push(`*Deal ID: ${deal.dealId}*`);
  lines.push('');
  lines.push('**Sources:**');
  for (const source of deal.sources) {
    lines.push(`- ${source.id}: ${source.kind}${source.filename ? ` (${source.filename})` : ''} — imported ${new Date(source.importedAt).toLocaleString()}`);
  }
  
  return lines.join('\n');
}

// ============================================================================
// Helper functions
// ============================================================================

function formatMetricValue(metric: KeyMetric): string {
  const v = metric.value;
  const unit = v.unit || '';
  
  if (unit === 'USD' || unit === 'USD/year') {
    return formatCurrency(v.value);
  }
  if (unit === '%') {
    return `${v.value.toFixed(2)}%`;
  }
  if (unit === 'x') {
    return `${v.value.toFixed(2)}x`;
  }
  
  return v.value.toLocaleString(undefined, { maximumFractionDigits: 2 });
}

function formatCurrency(value: number): string {
  if (value >= 1_000_000) {
    return `$${(value / 1_000_000).toFixed(2)}M`;
  }
  if (value >= 1_000) {
    return `$${(value / 1_000).toFixed(0)}K`;
  }
  return `$${value.toFixed(0)}`;
}

function formatAssessment(assessment?: string): string {
  switch (assessment) {
    case 'good': return '✅ Good';
    case 'acceptable': return '👍 Acceptable';
    case 'concerning': return '⚠️ Concerning';
    case 'critical': return '🔴 Critical';
    case 'unknown': return '❓ Unknown';
    default: return '—';
  }
}

function generateConfidenceBar(confidence: number): string {
  const filled = Math.round(confidence * 10);
  const empty = 10 - filled;
  return '█'.repeat(filled) + '░'.repeat(empty);
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
